### ISSUE TITLE
Использовать рандеву канал для команд рискованно

### ISSUE THREAD

**Issue by romansl** [NekrutovEd/EasyFinance#1]
Пример из кода:
```kotlin    
private val _error: Channel<String> = Channel()
```

В этом случае есть риск потерять сообщение если их будет несколько подряд и при этом не будет ни одного подписчика.

Лучше использовать канал максимального размера.

**Comment by NekrutovEd** [comment]
Не обратил на это внимание. Поправил в https://github.com/NekrutovEd/EasyFinance/pull/2 Спасибо)
